name: Frontend terraform - destroy

on:
  workflow_dispatch:
  #schedule:
    # At 00:00 (midnight) every day
    #- cron: '0 0 * * *'

jobs:
  terraform:
    name: Distroy the project
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.ROLE_TO_ASSUME }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: eu-central-1

      - uses: hashicorp/setup-terraform@v2

      - run: terraform init -backend-config=backend-dev.conf -reconfigure
        working-directory: src/loregen/frontend/terraform

      - run: terraform plan
        working-directory: src/loregen/frontend/terraform

      - run: terraform destroy -auto-approve
        working-directory: src/loregen/frontend/terraform
